### ISSUE TITLE
UltraDMD replacement - error with Iron Maiden Virtual Time

### ISSUE THREAD

**Issue by mkalkbrenner** [vbousquet/flexdmd#1]
Hi,

First of all, great work!

I just recognized a difference to UltraDMD when you use FlexDMD as replacement with the Iron Maiden Virtual Time table: https://vpinball.com/VPBdownloads/iron-maiden-virtual-time-v1-0-0-2020/

UltraDMD shows the Iron Maiden label at the DMD all the time when no other message is shown. FlexDMD only shows it for approximately one or two seconds.

**Comment by kds70** [comment]
Same here ...

**Comment by vbousquet** [comment]
This was a bug in the UltraDMD interface. It is now fixed in the 0.1.5 release.

**Comment by kds70** [comment]
Perfect ... =))
