### ISSUE TITLE
Dark Crystal

### ISSUE THREAD

**Issue by dav76df** [vbousquet/flexdmd#10]
Hello, can you add the script for the table Dark Crystal 1.2 of JP'Salas

**Comment by wiesshund** [comment]
That's WPilots table

But here, there is already a table script, though the tables font image files are not the best for it 
Little hard to  read

[Dark Crystal 1.2.vbs.zip](https://github.com/vbousquet/flexdmd/files/5455587/Dark.Crystal.1.2.vbs.zip)

**Comment by vbousquet** [comment]
Thanks @wiesshund : I have used your script, modified it a bit (size of the dots), improved FlexDMD to have a better rendering, and publish all of that in the 1.6.0 release.

**Comment by dav76df** [comment]
thanks

i install it

Le mer. 11 nov. 2020 à 17:21, Vincent Bousquet <notifications@github.com> a
écrit :

**Comment by dav76df** [comment]
Bonjour,

Merci pour la modif de Dark Cristal, sur un DMD LCD le rendu est meilleur. La modif  du script dark crystal est aussi possible sur le script de Ghosbuster ?

**Comment by vbousquet** [comment]
The script for JP's Ghostbuster is already available in GitHub and in the zip with each release. Just drop it with the table and everything should be fine.

**Comment by dav76df** [comment]
yes i know, but the modif for the size of the dots, it is possibile to make
the same modification for Ghosbuster ?

Le mer. 11 nov. 2020 à 21:50, Vincent Bousquet <notifications@github.com> a
écrit :

**Comment by wiesshund** [comment]
You could just edit them in the script to be the same as dark crystal

**Comment by vbousquet** [comment]
The script has to be adapted to the table; FlexDMD rebuilt a dot image from the image provided inside the table. I have tried different sizes for Ghostbuster and the size 2 seems the better I can get. To get a better DMD, this would need to redraw the images in the table.

You can try as well if you want; just edit the script and look for dmd2=2 or dmd=2 and replace by dmd2=3 and dmd=3

**Comment by wiesshund** [comment]
@vbousquet 
JP is going to redo some of his tables after Xmas and redo the DMD content to be a more standard resolution
he made them with just a tiny desktop DMD in mind originally.
(Slimer Diablo Zelda etc)

So i would not worry so much about the scripts and DOT size at this point.

**Comment by dav76df** [comment]
thank you both for your answers, I understand the functionality better
