### ISSUE TITLE
Conflict with DMDext when trying to configure alphanumerics (FlexDMD 1.6)

### ISSUE THREAD

**Issue by wiesshund** [vbousquet/flexdmd#11]
I am not sure if it comes from the flexDMD side or the DMDext 1.8 side
but it seems you can not use the external DMD extensions, without flexDMD
displaying its DMD window also
Which is fine for other things but not alpha numerics

You can put 
[table name]
virtualdmd enabled = false

into dmddevice.ini, but it will not honor it
the flexDMD window still appears anyways.

And this is with table with no call to flexDMD at all, so they are not loading flexDMD or anything
In fact, the only way i got it to not show the flexDMD window was to have the table init flexDMD
and then have the table set flexdmd show to false

The flexDMD window looks quite nice and all, but is not appropriate for a segmented LED display

**Comment by wiesshund** [comment]
i can make believe not show the fexDMD window by setting virtual dmd X and Y sizes both to 0
it is still there, but it is not visible.

So that works, but seems the wrong way to go about it

**Comment by vbousquet** [comment]
As i understand the issue you report is linked to the configuration of dmddevice. I will close for now since FlexDMD just use DMDDevice and does not interfere in anyway on its configuration.
