### ISSUE TITLE
Won't Register

### ISSUE THREAD

**Issue by 4thkindenter** [vbousquet/flexdmd#14]
I have tried to install Flex DMD a few times and no matter what when I try to hit the register button it thinks for a second and does not register. Everything is up to date on  my computer and on the software side. What can I do?

**Comment by vbousquet** [comment]
I can't provide any help without a clean log. perhaps you will find more support on VPForums.

**Comment by 4thkindenter** [comment]
I posted on there as well. 
https://www.vpforums.org/index.php?showtopic=43569&page=27
I also posted the Windows Event log regarding Flex. Could you take a look?
