### ISSUE TITLE
COMException: The stream number provided was invalid. The stream number provided was invalid. 

### ISSUE THREAD

**Issue by freezy** [vbousquet/flexdmd#16]
Another one:

![image](https://user-images.githubusercontent.com/70426/110171925-b9f4f080-7dfc-11eb-8266-0ca660f34731.png)

**Comment by vbousquet** [comment]
Could you provide me with the table file to reproduce ? And which version of Flex and DmdExt were you using ?

**Comment by freezy** [comment]
[This is the error](https://app.raygun.com/crashreporting/krej70/errors/4258365195?dateFrom=2020-09-06T13%3A43%3A31.000Z&dateTo=2021-03-05T13%3A43%3A31.000Z). This particular crash was 1.7.3 and if you look at the log, it seems the game name was set to an empty string.

**Comment by vbousquet** [comment]
Fixed with commit https://github.com/vbousquet/flexdmd/commit/4d7f9280c589b338c167c3c4759300a1c847ac4d
