### ISSUE TITLE
Rendering may lag on PinDMD devices

### ISSUE THREAD

**Issue by vbousquet** [vbousquet/flexdmd#21]
Following this [post](https://www.vpforums.org/index.php?showtopic=43569&p=472062), there seems to be situation where FlexDMD sends to much images to dmddevice.dll which in turns flood PinDMD device.

The problem seems more on the way dmddevice.dll sends the data, processing one after the other even if it is lagging behind. Here is a Freezy's DMD build wich only sends the latest one to try to avoid this lag for testing with the video mode of the FlexDemo table (I do not have a PinDMD myself): [DmdDevice.zip](https://github.com/vbousquet/flexdmd/files/6224660/DmdDevice.zip)

Feedback will be welcomed !

**Comment by sverrewl** [comment]
That is what I would call a very nice improvement. Not only am I able to play the game right of pindmd3, it seems to work without any problem for Metallica and TWD, using "altcolor". Very nice Vincent !!

**Comment by vbousquet** [comment]
Thanks for the feedback ! I have made a [pull request](https://github.com/freezy/dmd-extensions/pull/278) to Freezy so that the code would be integrated in the main branch. I think it will also solve a few pending issue that were reported on Freezy's DMD. I will close the issue for FlexDMD. Regards !
