### ISSUE TITLE
Avoid stats for certain table

### ISSUE THREAD

**Issue by fernandojconti** [vbousquet/flexdmd#24]
I am using PinballY as frontend and I have enabled the script to display game stats in the DMD for all my tables before launching them, but I would like to know if there is any way around it only for certain tables where I have videos and I don't want that overlap.

**Comment by vbousquet** [comment]
Hi ! I am not developping the script for PinballY. You may find the latest addition in the PinballY example repository here: https://github.com/PinballY/PinballY-Addons-and-Examples

I will close the issue since It is not linked to FlexDMD but to the PinballY script.
