### ISSUE TITLE
FlexDMD errors on using GetLabel

### ISSUE THREAD

**Issue by wiesshund** [vbousquet/flexdmd#26]
FlexDMD errors on using GetLabel
Using GetLabel will result in an object required error

See
http://vpforums.org/imghost/98/10.png
http://vpforums.org/imghost/98/20.png

Happens on the latest 1.8.1 builds from the last 4 months

**Comment by vbousquet** [comment]
I will close this issue since this should be fixed in latest 1.9. Please tell me if you are still experiencing issues.
