### ISSUE TITLE
UltraDMD replacement: How to configure colors?

### ISSUE THREAD

**Issue by mkalkbrenner** [vbousquet/flexdmd#3]
If you use FlexDMD as UltraDMD replacement, how could you configure the "base" color that is used for test messages?

**Comment by vbousquet** [comment]
There is no way to configure the color like in UltraDMD (in the end FlexDMD is not UltraDMD). You can setup the color by modifying the script. An example is provided for America's most haunted in the script directory. Anyway, I will think about adding a configuration UI in the companion app.

**Comment by mkalkbrenner** [comment]
Thanks for the hint. I assume this is the magic:
```vbs
'Set UltraDMD = CreateObject("UltraDMD.DMDObject")
Dim FlexDMD
Set FlexDMD = CreateObject("FlexDMD.FlexDMD")
If FlexDMD is Nothing Then
	MsgBox "No UltraDMD found.  This table MAY run without it (but why would you want to??)."
        Exit Sub
End If
FlexDMD.Color = &h77FF22
Set UltraDMD = FlexDMD.NewUltraDMD()
UltraDMD.Init
```
