### ISSUE TITLE
(64 bit) Error ActiveX Component Can't Create Object FlexDMD.FlexDMD

### ISSUE THREAD

**Issue by studlygoorite** [vbousquet/flexdmd#31]
Hi, not sure where my issue is but my 32bit VPX and FlexDMD work great but with the newer tables demanding more memory I have installed a 64bit build beside my 32bit so I can use 64bit with the demanding tables and also for VR-GL (64bit).

When launching with the 64bit VPinballX.exe, tables "with FlexDMD" crash showing the error in the title, tables that do not use FlexDMD work fine.

I have a PinDMD3 and have the 64bit VPX, VPinMAME (registered as well), B2s and Freezy (maybe the issue is something to do with Freezy) but I am pretty sure I have all of the 32 and 64bit files installed that are required.

 Same goes with "some" VR-GL tables that use FlexDMD, JP's Serious Sam VR tables work fine but the new Game Of Thrones crashes with the error in the title. 
 
 Also, I have de-registered FlexDMD and re-registered a few times and have checkmarks beside all four categories. 
 
 Any help/suggestions would be greatly appreciated. Thanks

**Comment by vbousquet** [comment]
I have a pending update with lots of updates that may help. Do you use the latest ? https://github.com/vbousquet/flexdmd/actions/runs/3724396374

**Comment by studlygoorite** [comment]
> I have a pending update with lots of updates that may help. Do you use the latest ? https://github.com/vbousquet/flexdmd/actions/runs/3724396374

I'm sorry...and thanks, :) I was using 1.8.0 but this newer version 1.8.1 has at least fixed the issue of playing a FlexDMD enabled table with 64bit VPX.

**Comment by BasemntGamer78** [comment]
Is this 10.8.1 build available?

**Comment by studlygoorite** [comment]
> Is this 10.8.1 build available?

Grab the top most workflow in the "Actions" tab above.

**Comment by bossman500** [comment]
I see that the workflow is available that may solve the 64 bit problem, but I don't see a binary for 1.81 in actions.  thank in advance.
 _

**Comment by bossman500** [comment]
My mistake!  I thought I tried to load the binary zip but it would not go.  Tried it again the third time and it worked.  More importantly, the 64 bit works.

Thanks for all the good work!!!!!
