### ISSUE TITLE
Flex DMD 1.9 Text Alignment Issues - Latest action is better, but still has some issues

### ISSUE THREAD

**Issue by Smilelikejoker** [vbousquet/flexdmd#36]
This is what was in https://github.com/vbousquet/flexdmd/actions/runs/4332019741 .  You've already seen it, but for reference purposes, I'm adding a screenshot for comparison:
![example1](https://github.com/vbousquet/flexdmd/assets/102932021/ed5aa32a-2d01-4922-84d5-03c47c0af164)

This is comparison screenshot from the latest action (https://github.com/vbousquet/flexdmd/actions/runs/4640337250) in which issue 33 was closed.
![example2](https://github.com/vbousquet/flexdmd/assets/102932021/fc65feb2-d3ec-4a36-9049-1deb19656e29)

The left side doesn't seem to be cut off anymore.  However, the top is still being cut off some.  I did verify that it wasn't being cut-off in 1.8 to rule out the table as the issue. 

It is better than what it was, but not quite there yet.  Progress :)  SIDENOTE - Thanks for all your work on this.  It is much appreciated by the VP community.

**Comment by Smilelikejoker** [comment]
I ran across this today.  Same game (GOT LE).  The left text is cutoff in this frame.  It's more in the middle compared to the above.
![example3](https://github.com/vbousquet/flexdmd/assets/102932021/6a161949-b50c-472e-b736-182a374c0635)

**Comment by vbousquet** [comment]
This is fixed by https://github.com/vbousquet/flexdmd/actions/runs/5707435753
