### ISSUE TITLE
dmd position not saving

### ISSUE THREAD

**Issue by Tom-Neverwinter** [vbousquet/flexdmd#37]
Therefore to position the DMD, if you are using Freezy's DMD, simply run the table, right click on the DMD and select the option to save its position.

using three different pinup popper baller installer updates and I cannot either disable this thing or force it to any position other than what appears to be a 0,0 default? I dont see any negative number shenanigan's

**Comment by vbousquet** [comment]
I cna not help you. Flex DMD does not display the DMD. It is done by the DMD backend you are using (freezy or whatever)
