### ISSUE TITLE
1.9 build no longer available

### ISSUE THREAD

**Issue by francisdb** [vbousquet/flexdmd#38]
The previous build is expired and some guides point to it

https://github.com/vbousquet/flexdmd/actions/runs/4332019741

**Comment by Smilelikejoker** [comment]
That action was released 3 months ago.  Some guides out there haven't been updated to the latest build that was released 2 months ago.
https://github.com/vbousquet/flexdmd/actions/runs/4640337250

This release helps with the DMD text alignment issues that some games have.  Although not 100% fixed yet, it does help a lot.

**Comment by vbousquet** [comment]
Latest is available again. Note that these are continuous integration build, not release, so they are not expected to be available more than 3 monthes

**Comment by julianmrodri** [comment]
Sorry but it still shows as expired in all of the CI runs mentioned above and its not in releases, so where can I access the 1.9 version? Thanks!

**Comment by Smilelikejoker** [comment]
> Sorry but it still shows as expired in all of the CI runs mentioned above and its not in releases, so where can I access the 1.9 version? Thanks!
> 
> Can I use the artifact from this run? -> https://github.com/vbousquet/flexdmd/actions/runs/5707435753 ?

Yes.  That is the latest 1.9 action.

**Comment by francisdb** [comment]
The main issue is: why is this not being released properly?
