### ISSUE TITLE
Feature request: Hide FlexDMD window from Windows Task Switcher

### ISSUE THREAD

**Issue by jueank** [vbousquet/flexdmd#4]
FlexDMD is great! I love it already enough for its brilliant integration into PinballY! Thanks a lot!
Currently, while running - FlexDMD is shown like a 'main' application in Windows Task Switcher. I would prefer if it behaves like e.g. PinAffinity, having only a task tray symbol and not being shown in Task Switcher at all. For 'regular' use (playing a table) it's just managed by VPX, right? Alternatively - if its preferable to have it still accessible by ALT + TAB ( e.g. while developing a table), this could be a configurable option.
Longer explanation: While working on my cab (configuring tables, managing assets and such) - which is in general not very comfortable (landscape orientation, having to turn my head) - i would prefer to have as few apps as possible inbetween i have to switch using ALT + TAB. It's really mostly about convenience. Hope this sounds reasonable.

**Comment by jsb2092** [comment]
This is a flex dmd issue.  Not a pinbally issue.  You can open a ticket on the flexdmd repository though I doubt it would change due to the way it needs to work for somethings having an accessible window title in the taskbar.

**Comment by vbousquet** [comment]
After having a look at it, it is not a FlexDMD either, but a FreezyDMD one :). FlexDMD rely largely on the excellent DMD interface and rendering provided by FreezyDMD (https://github.com/freezy/dmd-extensions). It happens that the VirtualDMD from Freezy is using window that shows in the taskbar. I can not do anything for this. Sorry

**Comment by jueank** [comment]
Thank you for looking into it! I raised a feature request in freezys Github project for the dmd-extensions!
