### ISSUE TITLE
FlexDMD 1.9 - FlexDMD.FontDef Removed

### ISSUE THREAD

**Issue by alaw-lufc** [vbousquet/flexdmd#40]
Hi,
Has the FlexDMD.FontDef class been removed from flex 1.9 intentionally?. It's used by some plugins in PinballX to display table data in the front end using different fonts on a DMD and works ok in flex 1.8 by setting a font using FlexDMD objects .FontDef.Path

Difference can been seen in object browser comparing flex 1.8 and flex 1.9;

![image](https://github.com/vbousquet/flexdmd/assets/73988577/77605c28-7ca6-4ab1-bc6e-5db42f0ec075)

**Comment by vbousquet** [comment]
The initial asset manager had a few bugs. There were situation where resources would be leaked. It was not designed to account for packed ressource (texture atlas). So it was entirely rewritten in 1.9. The ressource are now identified by an AssetSrc object (which has all parameters FontDef used to have).
