### ISSUE TITLE
VPX Table Stuck at "Starting Game Scripts" after saving the table in the editor

### ISSUE THREAD

**Issue by TheLardos** [vbousquet/flexdmd#47]
Hi,
I'm currently trying to run the table: "John Wick (BABAYAGA Pinball edition)" and I've heard I need to update my FlexDMD in order to be able to save the table in the editor.

I've installed the newest version of FlexDMD. I've also updated my Freezy's DMD Extensions. When launching the FlexDMDui.exe all points are checked with a green checkmark so I assume everything should be installed correctly.

However once I "save" my table in the VPX 10.8 editor, it doesn't launch anymore and gets stucked at "Starting Game Scripts".

Any idea what I'm doing wrong?

Best regards,
Luca

**Comment by openpowerwtf** [comment]
I had the same problem with Deadpool.  Clone/rebuild/reinstall fixed it.
