### ISSUE TITLE
possible issue when relaunching a table multiple times with out closing VPX, like when editing and testing

### ISSUE THREAD

**Issue by wiesshund** [vbousquet/flexdmd#7]
the DMD will cease playing, and kind of lock up VPX, have to end task everything.

it's fine if you just launch it and play it, can run it for days.
can also close and reopen vpx all you want, no issues

but if you are going in and out of same table, like when editing etc, it will freeze up, like it is maybe not releasing or clearing something when it shuts down.

I will give a table that should be guaranteed to trigger the issue
just launch the table, return to editor then relaunch the table a few times.

https://www.vpforums.org/index.php?app=downloads&showfile=15165

It also seems to be more prone if flexDMD is displaying any kind of video content as opposed to still images

Freezy's 1.8 DMD extensions are installed

**Comment by wiesshund** [comment]
Just a note that issue still present in 1.5 version of flexDMD

**Comment by wiesshund** [comment]
Attaching a log file of flexDMD dying

[FlexDMD.log](https://github.com/vbousquet/flexdmd/files/5435642/FlexDMD.log)

**Comment by vbousquet** [comment]
Thanks for the log. I will have a look hen I'm back ; it shows a clear lifecycle bug with Microsoft Media Framework.

**Comment by vbousquet** [comment]
I've just published the release 1.6.0 which fixes this bug (with a bunch of other goodies)
