### ISSUE TITLE
FlexDMDUI.exe crashes when opening it

### ISSUE THREAD

**Issue by sxr1993** [vbousquet/flexdmd#9]
After opening the file one time, pressing "Register FlexDMD" and gettting a cryptic error I didn't screenshot, the file now just crashes every time I open it and WerFault.exe says this:
![image](https://user-images.githubusercontent.com/51852802/92321852-fc986480-f035-11ea-8443-5f8b0de201ed.png)
"Problem details":
`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	FlexDMDUI.exe
  Problem Signature 02:	1.5.0.0
  Problem Signature 03:	f5020f52
  Problem Signature 04:	System
  Problem Signature 05:	4.8.3928.0
  Problem Signature 06:	5d390174
  Problem Signature 07:	2ebc
  Problem Signature 08:	21
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789`

Tried redownloading the file, opening it with admin permissions, in different locations, with compability mode, nothing worked so far. OS is x32 Windows 7, FlexDMD version 1.5.0. Sorry for lack of any reproduction info, this is all I can get about the issue right now,

**Comment by vbousquet** [comment]
@sxr1993 Could you provide teh logs (FlexDMD.log and dmddevice.log) ? This would greatly help understand what is going on

**Comment by sxr1993** [comment]
(issue closed; managed to fix this with the older version)
